### ISSUE TITLE
Unhandled error detected

### ISSUE THREAD

**Issue by JensDM** [Luligu/matterbridge-shelly#60]
Hello,

I encountered the following error while setting up after installing the Shelly plugin in Matterbridge:
` 
[07:37:16.715] [shellyswitch25-E8DB84A20980] - model: SHSW-25

[07:37:16.715] [shellyswitch25-E8DB84A20980] - firmware: v1.14.0-gcb84623
[07:37:16.716] [shellyswitch25-E8DB84A20980] - profile: switch
[07:37:16.716] [shellyswitch25-E8DB84A20980] - components:
[07:37:16.717] [shellyswitch25-E8DB84A20980]   - wifi_ap (WiFi)
[07:37:16.717] [shellyswitch25-E8DB84A20980]   - wifi_sta (WiFi)
[07:37:16.718] [shellyswitch25-E8DB84A20980]   - wifi_sta1 (WiFi)
[07:37:16.718] [shellyswitch25-E8DB84A20980]   - mqtt (MQTT)
[07:37:16.719] [shellyswitch25-E8DB84A20980]   - coiot (CoIoT)
[07:37:16.719] [shellyswitch25-E8DB84A20980]   - sntp (Sntp)
[07:37:16.720] [shellyswitch25-E8DB84A20980]   - cloud (Cloud)
[07:37:16.720] [shellyswitch25-E8DB84A20980]   - relay:0 (Relay)
[07:37:16.720] [shellyswitch25-E8DB84A20980]   - relay:1 (Relay)
[07:37:16.721] [shellyswitch25-E8DB84A20980]   - meter:0 (PowerMeter)
[07:37:16.721] [shellyswitch25-E8DB84A20980]   - meter:1 (PowerMeter)
[07:37:16.721] [shellyswitch25-E8DB84A20980]   - input:0 (Input)
[07:37:16.722] [shellyswitch25-E8DB84A20980]   - input:1 (Input)
[07:37:16.723] [shellyswitch25-E8DB84A20980]   - sys (Sys)
[07:37:16.780] [Matterbridge] Added and registered bridged device (1/1) shellyswitch25-E8DB84A20980 (MA-bridgedNode) for plugin matterbridge-shelly
[07:37:16.782] [Matterbridge shelly plugin] Loaded from cache Shelly device shellyswitch25-3C6105E4F0F1 host 192.168.6.10
[07:37:16.783] [shellyswitch25-3C6105E4F0F1] Shelly added shellyswitch25-3C6105E4F0F1 device id shellyswitch25-3C6105E4F0F1 host 192.168.6.10
[07:37:16.783] [shellyswitch25-3C6105E4F0F1] - gen: 1
[07:37:16.783] [shellyswitch25-3C6105E4F0F1] - mac: 3C6105E4F0F1
[07:37:16.784] [shellyswitch25-3C6105E4F0F1] - model: SHSW-25
[07:37:16.784] [shellyswitch25-3C6105E4F0F1] - firmware: v1.14.0-gcb84623
[07:37:16.784] [shellyswitch25-3C6105E4F0F1] - profile: cover
[07:37:16.784] [shellyswitch25-3C6105E4F0F1] - components:
[07:37:16.785] [shellyswitch25-3C6105E4F0F1]   - wifi_ap (WiFi)
[07:37:16.785] [shellyswitch25-3C6105E4F0F1]   - wifi_sta (WiFi)
[07:37:16.785] [shellyswitch25-3C6105E4F0F1]   - wifi_sta1 (WiFi)
[07:37:16.786] [shellyswitch25-3C6105E4F0F1]   - mqtt (MQTT)
[07:37:16.786] [shellyswitch25-3C6105E4F0F1]   - coiot (CoIoT)
[07:37:16.786] [shellyswitch25-3C6105E4F0F1]   - sntp (Sntp)
[07:37:16.787] [shellyswitch25-3C6105E4F0F1]   - cloud (Cloud)
[07:37:16.787] [shellyswitch25-3C6105E4F0F1]   - roller:0 (Roller)
[07:37:16.787] [shellyswitch25-3C6105E4F0F1]   - meter:0 (PowerMeter)
[07:37:16.787] [shellyswitch25-3C6105E4F0F1]   - input:0 (Input)
[07:37:16.788] [shellyswitch25-3C6105E4F0F1]   - input:1 (Input)
[07:37:16.788] [shellyswitch25-3C6105E4F0F1]   - sys (Sys)
[07:37:16.815] [Matterbridge] Added and registered bridged device (2/2) shellyswitch25-3C6105E4F0F1 (MA-bridgedNode) for plugin matterbridge-shelly
[07:37:16.816] [Matterbridge shelly plugin] Loaded from cache Shelly device shellyswitch25-3C6105E4E892 host 192.168.6.11
[07:37:16.817] [shellyswitch25-3C6105E4E892] Shelly added shellyswitch25-3C6105E4E892 device id shellyswitch25-3C6105E4E892 host 192.168.6.11
[07:37:16.817] [shellyswitch25-3C6105E4E892] - gen: 1
[07:37:16.817] [shellyswitch25-3C6105E4E892] - mac: 3C6105E4E892
[07:37:16.818] [shellyswitch25-3C6105E4E892] - model: SHSW-25
[07:37:16.818] [shellyswitch25-3C6105E4E892] - firmware: v1.14.0-gcb84623
[07:37:16.818] [shellyswitch25-3C6105E4E892] - profile: cover
[07:37:16.818] [shellyswitch25-3C6105E4E892] - components:
[07:37:16.819] [shellyswitch25-3C6105E4E892]   - wifi_ap (WiFi)
[07:37:16.819] [shellyswitch25-3C6105E4E892]   - wifi_sta (WiFi)
[07:37:16.819] [shellyswitch25-3C6105E4E892]   - wifi_sta1 (WiFi)
[07:37:16.819] [shellyswitch25-3C6105E4E892]   - mqtt (MQTT)
[07:37:16.820] [shellyswitch25-3C6105E4E892]   - coiot (CoIoT)
[07:37:16.820] [shellyswitch25-3C6105E4E892]   - sntp (Sntp)
[07:37:16.820] [shellyswitch25-3C6105E4E892]   - cloud (Cloud)
[07:37:16.820] [shellyswitch25-3C6105E4E892]   - roller:0 (Roller)
[07:37:16.820] [shellyswitch25-3C6105E4E892]   - meter:0 (PowerMeter)
[07:37:16.821] [shellyswitch25-3C6105E4E892]   - input:0 (Input)
[07:37:16.821] [shellyswitch25-3C6105E4E892]   - input:1 (Input)
[07:37:16.821] [shellyswitch25-3C6105E4E892]   - sys (Sys)
[07:37:16.845] [Matterbridge] Added and registered bridged device (3/3) shellyswitch25-3C6105E4E892 (MA-bridgedNode) for plugin matterbridge-shelly
[07:37:16.847] [Matterbridge shelly plugin] Loaded from cache Shelly device shellyswitch25-3C6105E534F6 host 192.168.6.12
[07:37:16.848] [ShellyKüche1] Shelly added ShellyKüche1 device id shellyswitch25-3C6105E534F6 host 192.168.6.12
[07:37:16.848] [ShellyKüche1] - gen: 1
[07:37:16.848] [ShellyKüche1] - mac: 3C6105E534F6
[07:37:16.849] [ShellyKüche1] - model: SHSW-25
[07:37:16.849] [ShellyKüche1] - firmware: v1.14.0-gcb84623
[07:37:16.849] [ShellyKüche1] - profile: switch
[07:37:16.850] [ShellyKüche1] - components:
[07:37:16.850] [ShellyKüche1]   - wifi_ap (WiFi)
[07:37:16.850] [ShellyKüche1]   - wifi_sta (WiFi)
[07:37:16.851] [ShellyKüche1]   - wifi_sta1 (WiFi)
[07:37:16.851] [ShellyKüche1]   - mqtt (MQTT)
[07:37:16.851] [ShellyKüche1]   - coiot (CoIoT)
[07:37:16.851] [ShellyKüche1]   - sntp (Sntp)
[07:37:16.852] [ShellyKüche1]   - cloud (Cloud)
[07:37:16.852] [ShellyKüche1]   - relay:0 (Relay)
[07:37:16.852] [ShellyKüche1]   - relay:1 (Relay)
[07:37:16.853] [ShellyKüche1]   - meter:0 (PowerMeter)
[07:37:16.853] [ShellyKüche1]   - meter:1 (PowerMeter)
[07:37:16.853] [ShellyKüche1]   - input:0 (Input)
[07:37:16.854] [ShellyKüche1]   - input:1 (Input)
[07:37:16.854] [ShellyKüche1]   - sys (Sys)
[07:37:16.882] [Matterbridge] Added and registered bridged device (4/4) ShellyKüche1 (MA-bridgedNode) for plugin matterbridge-shelly
[07:37:17.047] [Logger] Unhandled error detected: Cannot read properties of undefined (reading 'cfg_rev')
  at ShellyDevice.create (file:///usr/local/lib/node_modules/matterbridge-shelly/dist/shellyDevice.js:665:88)
  at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
  at async ShellyPlatform.addDevice (file:///usr/local/lib/node_modules/matterbridge-shelly/dist/platform.js:1298:22)
  at async Shelly.<anonymous> (file:///usr/local/lib/node_modules/matterbridge-shelly/dist/platform.js:118:17)
file:///usr/local/lib/node_modules/matterbridge-shelly/dist/shellyDevice.js:665
            componentsPayload = { components: btHomeComponents, cfg_rev: btHomePayload.cfg_rev, offset: 0, total: btHomeComponents.length };
                                                                                       ^
TypeError: Cannot read properties of undefined (reading 'cfg_rev')
    at ShellyDevice.create (file:///usr/local/lib/node_modules/matterbridge-shelly/dist/shellyDevice.js:665:88)
    at process.processTicksAndRejections (node:internal/process/task_queues:105:5)
    at async ShellyPlatform.addDevice (file:///usr/local/lib/node_modules/matterbridge-shelly/dist/platform.js:1298:22)
    at async Shelly.<anonymous> (file:///usr/local/lib/node_modules/matterbridge-shelly/dist/platform.js:118:17)
Node.js v22.9.0
`

**Comment by Luligu** [comment]
Hi,
thanks for reporting the issue.

Can you tell me the version matterbridge and matterbridge-shelly plugin?

Can you provide me the full log please?

https://github.com/Luligu/matterbridge?tab=readme-ov-file#how-to-send-the-debug-log-files

**Comment by Luligu** [comment]
Fixed.
## [1.0.2] - 2024-10-13

### Added

- [shelly]: Added scheduled_restart event from Sys to set the devices that will not be loaded from cache at restart.
- [shelly]: Added component Devicepower.
- [shellyplussmoke]: Added battery readings (battery level and voltage) to shellyplussmoke and shellyhtg3 (all devices with Devicepower component).

### Fixed

- [BTHome]: Fixed issue to BTHome components discovery.

<a href="https://www.buymeacoffee.com/luligugithub">
  <img src="./yellow-button.png" alt="Buy me a coffee" width="120">
</a>
