### ISSUE TITLE
mattebridge-shelly crashing

### ISSUE THREAD

**Issue by joargp** [Luligu/matterbridge-shelly#81]
[08:42:07.525] [Logger] Unhandled error detected: Cannot read properties of undefined (reading 'cfg_rev')
  at ShellyDevice.fetchUpdate (file:///usr/local/lib/node_modules/matterbridge-shelly/dist/shellyDevice.js:1105:93)
  at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
file:///usr/local/lib/node_modules/matterbridge-shelly/dist/shellyDevice.js:1105
            this.componentsPayload = { components: btHomeComponents, cfg_rev: btHomePayload.cfg_rev, offset: 0, total: btHomeComponents.length };
                                                                                            ^

TypeError: Cannot read properties of undefined (reading 'cfg_rev')
    at ShellyDevice.fetchUpdate (file:///usr/local/lib/node_modules/matterbridge-shelly/dist/shellyDevice.js:1105:93)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by Luligu** [comment]
Hi,
it shouldn't happen in any case.
Can you tell me what version you had of the plugin please ?
Thanks

**Comment by Luligu** [comment]
Ok so all good.
Thanks for your reply.
